var annotated_dup =
[
    [ "__gnu_cxx", "namespace____gnu__cxx.html", [
      [ "__ops", "namespace____gnu__cxx_1_1____ops.html", [
        [ "_Iter_comp_iter", "struct____gnu__cxx_1_1____ops_1_1___iter__comp__iter.html", "struct____gnu__cxx_1_1____ops_1_1___iter__comp__iter" ],
        [ "_Iter_comp_to_iter", "struct____gnu__cxx_1_1____ops_1_1___iter__comp__to__iter.html", "struct____gnu__cxx_1_1____ops_1_1___iter__comp__to__iter" ],
        [ "_Iter_comp_to_val", "struct____gnu__cxx_1_1____ops_1_1___iter__comp__to__val.html", "struct____gnu__cxx_1_1____ops_1_1___iter__comp__to__val" ],
        [ "_Iter_comp_val", "struct____gnu__cxx_1_1____ops_1_1___iter__comp__val.html", "struct____gnu__cxx_1_1____ops_1_1___iter__comp__val" ],
        [ "_Iter_equal_to_iter", "struct____gnu__cxx_1_1____ops_1_1___iter__equal__to__iter.html", "struct____gnu__cxx_1_1____ops_1_1___iter__equal__to__iter" ],
        [ "_Iter_equal_to_val", "struct____gnu__cxx_1_1____ops_1_1___iter__equal__to__val.html", "struct____gnu__cxx_1_1____ops_1_1___iter__equal__to__val" ],
        [ "_Iter_equals_iter", "struct____gnu__cxx_1_1____ops_1_1___iter__equals__iter.html", "struct____gnu__cxx_1_1____ops_1_1___iter__equals__iter" ],
        [ "_Iter_equals_val", "struct____gnu__cxx_1_1____ops_1_1___iter__equals__val.html", "struct____gnu__cxx_1_1____ops_1_1___iter__equals__val" ],
        [ "_Iter_less_iter", "struct____gnu__cxx_1_1____ops_1_1___iter__less__iter.html", "struct____gnu__cxx_1_1____ops_1_1___iter__less__iter" ],
        [ "_Iter_less_val", "struct____gnu__cxx_1_1____ops_1_1___iter__less__val.html", "struct____gnu__cxx_1_1____ops_1_1___iter__less__val" ],
        [ "_Iter_negate", "struct____gnu__cxx_1_1____ops_1_1___iter__negate.html", "struct____gnu__cxx_1_1____ops_1_1___iter__negate" ],
        [ "_Iter_pred", "struct____gnu__cxx_1_1____ops_1_1___iter__pred.html", "struct____gnu__cxx_1_1____ops_1_1___iter__pred" ],
        [ "_Val_comp_iter", "struct____gnu__cxx_1_1____ops_1_1___val__comp__iter.html", "struct____gnu__cxx_1_1____ops_1_1___val__comp__iter" ],
        [ "_Val_less_iter", "struct____gnu__cxx_1_1____ops_1_1___val__less__iter.html", "struct____gnu__cxx_1_1____ops_1_1___val__less__iter" ]
      ] ]
    ] ],
    [ "Bankable", "namespace_bankable.html", [
      [ "ManyAddresses", "namespace_bankable_1_1_many_addresses.html", [
        [ "DualManyAddresses", "class_bankable_1_1_many_addresses_1_1_dual_many_addresses.html", "class_bankable_1_1_many_addresses_1_1_dual_many_addresses" ],
        [ "ManyAddresses", "class_bankable_1_1_many_addresses_1_1_many_addresses.html", "class_bankable_1_1_many_addresses_1_1_many_addresses" ],
        [ "ManyMatrixAddresses", "class_bankable_1_1_many_addresses_1_1_many_matrix_addresses.html", "class_bankable_1_1_many_addresses_1_1_many_matrix_addresses" ]
      ] ],
      [ "CCSmartPotentiometer", "class_bankable_1_1_c_c_smart_potentiometer.html", "class_bankable_1_1_c_c_smart_potentiometer" ],
      [ "DualAddresses", "class_bankable_1_1_dual_addresses.html", "class_bankable_1_1_dual_addresses" ],
      [ "MatrixAddress", "class_bankable_1_1_matrix_address.html", "class_bankable_1_1_matrix_address" ],
      [ "MIDIIncrementDecrementButtons", "class_bankable_1_1_m_i_d_i_increment_decrement_buttons.html", "class_bankable_1_1_m_i_d_i_increment_decrement_buttons" ],
      [ "SingleAddress", "class_bankable_1_1_single_address.html", "class_bankable_1_1_single_address" ],
      [ "SingleAddressMultipleBanks", "class_bankable_1_1_single_address_multiple_banks.html", "class_bankable_1_1_single_address_multiple_banks" ],
      [ "SmartMIDIFilteredAnalog", "class_bankable_1_1_smart_m_i_d_i_filtered_analog.html", "class_bankable_1_1_smart_m_i_d_i_filtered_analog" ]
    ] ],
    [ "ble_backend", "namespaceble__backend.html", [
      [ "ESP32BluedroidBLE", "structble__backend_1_1_e_s_p32_bluedroid_b_l_e.html", null ],
      [ "ESP32NimBLE", "structble__backend_1_1_e_s_p32_nim_b_l_e.html", null ]
    ] ],
    [ "compat", "namespacecompat.html", [
      [ "in_place_t", "structcompat_1_1in__place__t.html", "structcompat_1_1in__place__t" ],
      [ "in_place_type_t", "structcompat_1_1in__place__type__t.html", "structcompat_1_1in__place__type__t" ],
      [ "remove_cvref", "structcompat_1_1remove__cvref.html", "structcompat_1_1remove__cvref" ]
    ] ],
    [ "ExtIO", "namespace_ext_i_o.html", [
      [ "CachedExtIOPin", "struct_ext_i_o_1_1_cached_ext_i_o_pin.html", "struct_ext_i_o_1_1_cached_ext_i_o_pin" ]
    ] ],
    [ "MIDI_Notes", "namespace_m_i_d_i___notes.html", [
      [ "Note", "class_m_i_d_i___notes_1_1_note.html", "class_m_i_d_i___notes_1_1_note" ]
    ] ],
    [ "Accelerometer3AxisSensor", "class_accelerometer3_axis_sensor.html", "class_accelerometer3_axis_sensor" ],
    [ "Adafruit_TinyUSB_USBDeviceMIDIBackend", "struct_adafruit___tiny_u_s_b___u_s_b_device_m_i_d_i_backend.html", "struct_adafruit___tiny_u_s_b___u_s_b_device_m_i_d_i_backend" ],
    [ "AnyMIDIMessage", "struct_any_m_i_d_i_message.html", "struct_any_m_i_d_i_message" ],
    [ "ArduinoBLEBackend", "class_arduino_b_l_e_backend.html", "class_arduino_b_l_e_backend" ],
    [ "Array", "struct_array.html", "struct_array" ],
    [ "ArraySlice", "class_array_slice.html", "class_array_slice" ],
    [ "Bank", "class_bank.html", "class_bank" ],
    [ "BankableMatchingMIDIInputElement", "class_bankable_matching_m_i_d_i_input_element.html", "class_bankable_matching_m_i_d_i_input_element" ],
    [ "BankableMIDIInput", "class_bankable_m_i_d_i_input.html", null ],
    [ "BankConfig", "struct_bank_config.html", "struct_bank_config" ],
    [ "BankSettingChangeCallback", "class_bank_setting_change_callback.html", "class_bank_setting_change_callback" ],
    [ "BaseBankConfig", "class_base_bank_config.html", "class_base_bank_config" ],
    [ "BaseOutputBankConfig", "class_base_output_bank_config.html", "class_base_output_bank_config" ],
    [ "BitArray", "class_bit_array.html", "class_bit_array" ],
    [ "BLECharacteristicHandle", "struct_b_l_e_characteristic_handle.html", "struct_b_l_e_characteristic_handle" ],
    [ "BLEConnectionHandle", "struct_b_l_e_connection_handle.html", "struct_b_l_e_connection_handle" ],
    [ "BLEDataGenerator", "class_b_l_e_data_generator.html", "class_b_l_e_data_generator" ],
    [ "BLEDataView", "struct_b_l_e_data_view.html", "struct_b_l_e_data_view" ],
    [ "BLEMIDIPacketBuilder", "class_b_l_e_m_i_d_i_packet_builder.html", "class_b_l_e_m_i_d_i_packet_builder" ],
    [ "BLEMIDIParser", "class_b_l_e_m_i_d_i_parser.html", "class_b_l_e_m_i_d_i_parser" ],
    [ "BLERingBuf", "class_b_l_e_ring_buf.html", "class_b_l_e_ring_buf" ],
    [ "BLESettings", "struct_b_l_e_settings.html", "struct_b_l_e_settings" ],
    [ "BTstackBackgroundBackend", "class_b_tstack_background_backend.html", "class_b_tstack_background_backend" ],
    [ "BufferedBLEMIDIParser", "class_buffered_b_l_e_m_i_d_i_parser.html", "class_buffered_b_l_e_m_i_d_i_parser" ],
    [ "BufferPuller_", "class_buffer_puller__.html", "class_buffer_puller__" ],
    [ "Button", "class_button.html", "class_button" ],
    [ "Cable", "class_cable.html", "class_cable" ],
    [ "CachedExtIOPin", "struct_cached_ext_i_o_pin.html", "struct_cached_ext_i_o_pin" ],
    [ "CCAccelerometerSender", "class_c_c_accelerometer_sender.html", "class_c_c_accelerometer_sender" ],
    [ "CCPotentiometer", "class_c_c_potentiometer.html", "class_c_c_potentiometer" ],
    [ "CCPotentiometer14", "class_c_c_potentiometer14.html", "class_c_c_potentiometer14" ],
    [ "CCUltrasonic", "class_c_c_ultrasonic.html", "class_c_c_ultrasonic" ],
    [ "Channel", "class_channel.html", "class_channel" ],
    [ "ChannelMessage", "struct_channel_message.html", "struct_channel_message" ],
    [ "ChannelPressureSender", "class_channel_pressure_sender.html", "class_channel_pressure_sender" ],
    [ "ChannelPressureSensor", "class_channel_pressure_sensor.html", "class_channel_pressure_sensor" ],
    [ "ContinuousCCSender", "class_continuous_c_c_sender.html", "class_continuous_c_c_sender" ],
    [ "ContinuousCCSender14", "class_continuous_c_c_sender14.html", "class_continuous_c_c_sender14" ],
    [ "DigitalNoteSender", "class_digital_note_sender.html", "class_digital_note_sender" ],
    [ "Display", "struct_display.html", null ],
    [ "DoublyLinkable", "class_doubly_linkable.html", "class_doubly_linkable" ],
    [ "DoublyLinkedList", "class_doubly_linked_list.html", "class_doubly_linked_list" ],
    [ "EMA", "class_e_m_a.html", "class_e_m_a" ],
    [ "EMA_f", "class_e_m_a__f.html", "class_e_m_a__f" ],
    [ "EmptySelectorCallback", "struct_empty_selector_callback.html", "struct_empty_selector_callback" ],
    [ "EncoderPinList", "struct_encoder_pin_list.html", "struct_encoder_pin_list" ],
    [ "EncoderSwitchPinList", "struct_encoder_switch_pin_list.html", "struct_encoder_switch_pin_list" ],
    [ "ErrorException", "class_error_exception.html", "class_error_exception" ],
    [ "ESP32_USBDeviceMIDIBackend", "struct_e_s_p32___u_s_b_device_m_i_d_i_backend.html", "struct_e_s_p32___u_s_b_device_m_i_d_i_backend" ],
    [ "ESP32BLEBackend", "class_e_s_p32_b_l_e_backend.html", "class_e_s_p32_b_l_e_backend" ],
    [ "ExtendedIOElement", "class_extended_i_o_element.html", "class_extended_i_o_element" ],
    [ "FilteredAnalog", "class_filtered_analog.html", "class_filtered_analog" ],
    [ "FineGrainedMIDI_Callbacks", "class_fine_grained_m_i_d_i___callbacks.html", "class_fine_grained_m_i_d_i___callbacks" ],
    [ "Frequency", "class_frequency.html", "class_frequency" ],
    [ "function_traits", "structfunction__traits.html", null ],
    [ "function_traits< Return(Args...)>", "structfunction__traits_3_01_return_07_args_8_8_8_08_4.html", "structfunction__traits_3_01_return_07_args_8_8_8_08_4" ],
    [ "GenericBLEMIDI_Interface", "class_generic_b_l_e_m_i_d_i___interface.html", "class_generic_b_l_e_m_i_d_i___interface" ],
    [ "GenericFilteredAnalog", "class_generic_filtered_analog.html", "class_generic_filtered_analog" ],
    [ "GenericIncrementDecrementSelector", "class_generic_increment_decrement_selector.html", "class_generic_increment_decrement_selector" ],
    [ "GenericSelector", "class_generic_selector.html", "class_generic_selector" ],
    [ "GenericUSBMIDI_Interface", "class_generic_u_s_b_m_i_d_i___interface.html", "class_generic_u_s_b_m_i_d_i___interface" ],
    [ "HairlessMIDI_Interface", "class_hairless_m_i_d_i___interface.html", "class_hairless_m_i_d_i___interface" ],
    [ "HardwareSerialDebugMIDI_Interface", "class_hardware_serial_debug_m_i_d_i___interface.html", "class_hardware_serial_debug_m_i_d_i___interface" ],
    [ "HardwareSerialDebugMIDI_Output", "class_hardware_serial_debug_m_i_d_i___output.html", "class_hardware_serial_debug_m_i_d_i___output" ],
    [ "HardwareSerialMIDI_Interface", "class_hardware_serial_m_i_d_i___interface.html", "class_hardware_serial_m_i_d_i___interface" ],
    [ "has_method_begin", "structhas__method__begin.html", null ],
    [ "has_method_begin< T, void_t< decltype(std::declval< T >().begin())> >", "structhas__method__begin_3_01_t_00_01void__t_3_01decltype_07std_1_1declval_3_01_t_01_4_07_08_8begin_07_08_08_4_01_4.html", null ],
    [ "HexDump", "struct_hex_dump.html", "struct_hex_dump" ],
    [ "HexPuller", "class_hex_puller.html", "class_hex_puller" ],
    [ "Hysteresis", "class_hysteresis.html", "class_hysteresis" ],
    [ "Hysteresis< 0, T_in, T_out >", "class_hysteresis_3_010_00_01_t__in_00_01_t__out_01_4.html", "class_hysteresis_3_010_00_01_t__in_00_01_t__out_01_4" ],
    [ "IncrementDecrementButtons", "class_increment_decrement_buttons.html", "class_increment_decrement_buttons" ],
    [ "IncrementDecrementSelector", "class_increment_decrement_selector.html", "class_increment_decrement_selector" ],
    [ "LambdaPuller_", "class_lambda_puller__.html", "class_lambda_puller__" ],
    [ "ManyAddresses_Base", "class_many_addresses___base.html", "class_many_addresses___base" ],
    [ "MatchingMIDIInputElement", "class_matching_m_i_d_i_input_element.html", "class_matching_m_i_d_i_input_element" ],
    [ "MaximumFilteredAnalogIncRes", "struct_maximum_filtered_analog_inc_res.html", null ],
    [ "MIDI_Callbacks", "class_m_i_d_i___callbacks.html", "class_m_i_d_i___callbacks" ],
    [ "MIDI_Interface", "class_m_i_d_i___interface.html", "class_m_i_d_i___interface" ],
    [ "MIDI_Parser", "class_m_i_d_i___parser.html", "class_m_i_d_i___parser" ],
    [ "MIDI_Pipe", "class_m_i_d_i___pipe.html", "class_m_i_d_i___pipe" ],
    [ "MIDI_PipeFactory", "struct_m_i_d_i___pipe_factory.html", "struct_m_i_d_i___pipe_factory" ],
    [ "MIDI_Sender", "class_m_i_d_i___sender.html", "class_m_i_d_i___sender" ],
    [ "MIDI_Sink", "class_m_i_d_i___sink.html", "class_m_i_d_i___sink" ],
    [ "MIDI_Source", "class_m_i_d_i___source.html", "class_m_i_d_i___source" ],
    [ "MIDIAddress", "class_m_i_d_i_address.html", "class_m_i_d_i_address" ],
    [ "MIDIBLEInstance", "class_m_i_d_i_b_l_e_instance.html", "class_m_i_d_i_b_l_e_instance" ],
    [ "MIDIButton", "class_m_i_d_i_button.html", "class_m_i_d_i_button" ],
    [ "MIDIButtonInverse", "class_m_i_d_i_button_inverse.html", "class_m_i_d_i_button_inverse" ],
    [ "MIDIChannelCable", "class_m_i_d_i_channel_cable.html", "class_m_i_d_i_channel_cable" ],
    [ "MIDIFilteredAnalog", "class_m_i_d_i_filtered_analog.html", "class_m_i_d_i_filtered_analog" ],
    [ "MIDIIncrementDecrementButtons", "class_m_i_d_i_increment_decrement_buttons.html", "class_m_i_d_i_increment_decrement_buttons" ],
    [ "MIDIInputElement", "class_m_i_d_i_input_element.html", "class_m_i_d_i_input_element" ],
    [ "midimap_", "classmidimap__.html", "classmidimap__" ],
    [ "MIDIMessage", "struct_m_i_d_i_message.html", "struct_m_i_d_i_message" ],
    [ "MIDIOutputOnly", "class_m_i_d_i_output_only.html", "class_m_i_d_i_output_only" ],
    [ "MIDIStaller", "struct_m_i_d_i_staller.html", "struct_m_i_d_i_staller" ],
    [ "MIDIUSB_USBDeviceMIDIBackend", "struct_m_i_d_i_u_s_b___u_s_b_device_m_i_d_i_backend.html", "struct_m_i_d_i_u_s_b___u_s_b_device_m_i_d_i_backend" ],
    [ "MMA7660", "class_m_m_a7660.html", "class_m_m_a7660" ],
    [ "MMA7660_ACC_DATA", "struct_m_m_a7660___a_c_c___d_a_t_a.html", "struct_m_m_a7660___a_c_c___d_a_t_a" ],
    [ "MMA7660_DATA", "struct_m_m_a7660___d_a_t_a.html", "struct_m_m_a7660___d_a_t_a" ],
    [ "MMA7660_LOOKUP", "struct_m_m_a7660___l_o_o_k_u_p.html", "struct_m_m_a7660___l_o_o_k_u_p" ],
    [ "MotorFader", "struct_motor_fader.html", null ],
    [ "NonatomicBLERingBufSize", "struct_nonatomic_b_l_e_ring_buf_size.html", "struct_nonatomic_b_l_e_ring_buf_size" ],
    [ "NormalUpdatable", "struct_normal_updatable.html", null ],
    [ "NoteButton", "class_note_button.html", "class_note_button" ],
    [ "NoteButtonInverse", "class_note_button_inverse.html", "class_note_button_inverse" ],
    [ "OutputBank", "class_output_bank.html", "class_output_bank" ],
    [ "OutputBankableMIDIAddress", "class_output_bankable_m_i_d_i_address.html", "class_output_bankable_m_i_d_i_address" ],
    [ "OutputBankableMIDIAddress_Base", "class_output_bankable_m_i_d_i_address___base.html", "class_output_bankable_m_i_d_i_address___base" ],
    [ "OutputBankConfig", "struct_output_bank_config.html", "struct_output_bank_config" ],
    [ "PBPotentiometer", "class_p_b_potentiometer.html", "class_p_b_potentiometer" ],
    [ "PBUltrasonic", "class_p_b_ultrasonic.html", "class_p_b_ultrasonic" ],
    [ "PitchBendSender", "class_pitch_bend_sender.html", null ],
    [ "PitchBendUltrasonicSender", "class_pitch_bend_ultrasonic_sender.html", "class_pitch_bend_ultrasonic_sender" ],
    [ "PixelLocation", "struct_pixel_location.html", "struct_pixel_location" ],
    [ "PollingBLEMIDISender", "class_polling_b_l_e_m_i_d_i_sender.html", "class_polling_b_l_e_m_i_d_i_sender" ],
    [ "PolyAftertouchSensor", "class_poly_aftertouch_sensor.html", "class_poly_aftertouch_sensor" ],
    [ "PolyphonicPressureSender", "class_polyphonic_pressure_sender.html", "class_polyphonic_pressure_sender" ],
    [ "Potentiometer", "struct_potentiometer.html", null ],
    [ "PrintDebugMIDI_Base", "class_print_debug_m_i_d_i___base.html", "class_print_debug_m_i_d_i___base" ],
    [ "RealTimeMessage", "struct_real_time_message.html", "struct_real_time_message" ],
    [ "RelativeMIDIAddress", "class_relative_m_i_d_i_address.html", "class_relative_m_i_d_i_address" ],
    [ "ScopedThreadConfig", "struct_scoped_thread_config.html", "struct_scoped_thread_config" ],
    [ "Selectable", "class_selectable.html", "class_selectable" ],
    [ "Selector", "class_selector.html", "class_selector" ],
    [ "SelectorBase", "class_selector_base.html", "class_selector_base" ],
    [ "SerialDebugMIDI_Interface", "class_serial_debug_m_i_d_i___interface.html", "class_serial_debug_m_i_d_i___interface" ],
    [ "SerialDebugMIDI_Output", "class_serial_debug_m_i_d_i___output.html", "class_serial_debug_m_i_d_i___output" ],
    [ "SerialMIDI_Interface", "class_serial_m_i_d_i___interface.html", "class_serial_m_i_d_i___interface" ],
    [ "SerialMIDI_Parser", "class_serial_m_i_d_i___parser.html", "class_serial_m_i_d_i___parser" ],
    [ "Setbase", "struct_setbase.html", "struct_setbase" ],
    [ "Setbytesep", "struct_setbytesep.html", "struct_setbytesep" ],
    [ "Setprecision", "struct_setprecision.html", "struct_setprecision" ],
    [ "StreamDebugMIDI_Interface", "class_stream_debug_m_i_d_i___interface.html", "class_stream_debug_m_i_d_i___interface" ],
    [ "StreamDebugMIDI_Output", "class_stream_debug_m_i_d_i___output.html", "class_stream_debug_m_i_d_i___output" ],
    [ "StreamMIDI_Interface", "class_stream_m_i_d_i___interface.html", "class_stream_m_i_d_i___interface" ],
    [ "StreamPuller", "class_stream_puller.html", "class_stream_puller" ],
    [ "SysCommonMessage", "struct_sys_common_message.html", "struct_sys_common_message" ],
    [ "SysExBuffer", "class_sys_ex_buffer.html", "class_sys_ex_buffer" ],
    [ "SysExMessage", "struct_sys_ex_message.html", "struct_sys_ex_message" ],
    [ "Teensy2_USBDeviceMIDIBackend", "struct_teensy2___u_s_b_device_m_i_d_i_backend.html", "struct_teensy2___u_s_b_device_m_i_d_i_backend" ],
    [ "Teensy3_USBDeviceMIDIBackend", "struct_teensy3___u_s_b_device_m_i_d_i_backend.html", "struct_teensy3___u_s_b_device_m_i_d_i_backend" ],
    [ "ThreadedBLEMIDISender", "class_threaded_b_l_e_m_i_d_i_sender.html", "class_threaded_b_l_e_m_i_d_i_sender" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "TrueMIDI_SinkSource", "struct_true_m_i_d_i___sink_source.html", null ],
    [ "Ultrasonic", "class_ultrasonic.html", "class_ultrasonic" ],
    [ "UltrasonicCCSender", "class_ultrasonic_c_c_sender.html", "class_ultrasonic_c_c_sender" ],
    [ "Updatable", "class_updatable.html", "class_updatable" ],
    [ "UpdatableCRTP", "class_updatable_c_r_t_p.html", "class_updatable_c_r_t_p" ],
    [ "USBDebugMIDI_Interface", "class_u_s_b_debug_m_i_d_i___interface.html", "class_u_s_b_debug_m_i_d_i___interface" ],
    [ "USBDebugMIDI_Output", "class_u_s_b_debug_m_i_d_i___output.html", "class_u_s_b_debug_m_i_d_i___output" ],
    [ "USBHostMIDI_Interface", "class_u_s_b_host_m_i_d_i___interface.html", "class_u_s_b_host_m_i_d_i___interface" ],
    [ "USBHostMIDI_Interface_BigBuffer", "class_u_s_b_host_m_i_d_i___interface___big_buffer.html", "class_u_s_b_host_m_i_d_i___interface___big_buffer" ],
    [ "USBHostMIDIBackend", "class_u_s_b_host_m_i_d_i_backend.html", "class_u_s_b_host_m_i_d_i_backend" ],
    [ "USBMIDI_Interface", "class_u_s_b_m_i_d_i___interface.html", "class_u_s_b_m_i_d_i___interface" ],
    [ "USBMIDI_Parser", "class_u_s_b_m_i_d_i___parser.html", "class_u_s_b_m_i_d_i___parser" ],
    [ "USBMIDI_Sender", "class_u_s_b_m_i_d_i___sender.html", "class_u_s_b_m_i_d_i___sender" ],
    [ "USBSerialMIDI_Interface", "class_u_s_b_serial_m_i_d_i___interface.html", "class_u_s_b_serial_m_i_d_i___interface" ],
    [ "VelostatNote", "class_velostat_note.html", "class_velostat_note" ],
    [ "VelostatNoteSender", "class_velostat_note_sender.html", "class_velostat_note_sender" ]
];