var dir_63a820b5eb5cb0b621e2dbc6bb54a5c1 =
[
    [ "advertising.c", "advertising_8c.html", null ],
    [ "advertising.h", "advertising_8h.html", "advertising_8h" ],
    [ "app.cpp", "app_8cpp.html", null ],
    [ "app.h", "app_8h.html", "app_8h" ],
    [ "ble2902.c", "ble2902_8c.html", null ],
    [ "ble2902.h", "ble2902_8h.html", "ble2902_8h" ],
    [ "esp_enums2string.c", "esp__enums2string_8c.html", null ],
    [ "esp_enums2string.h", "esp__enums2string_8h.html", "esp__enums2string_8h" ],
    [ "events-debug.c", "events-debug_8c.html", null ],
    [ "events-debug.h", "events-debug_8h.html", "events-debug_8h" ],
    [ "events.c", "events_8c.html", null ],
    [ "events.h", "events_8h.html", "events_8h" ],
    [ "logging.h", "logging_8h.html", null ],
    [ "midi-app.c", "midi-app_8c.html", null ],
    [ "midi-connection.c", "midi-connection_8c.html", null ],
    [ "midi-events.c", "midi-events_8c.html", null ],
    [ "midi-init.c", "midi-init_8c.html", null ],
    [ "midi-mtu.c", "midi-mtu_8c.html", null ],
    [ "midi-notify.c", "midi-notify_8c.html", null ],
    [ "midi-private.h", "midi-private_8h.html", "midi-private_8h" ],
    [ "midi-read.c", "midi-read_8c.html", null ],
    [ "midi-write.c", "midi-write_8c.html", null ],
    [ "midi.h", "midi_8h.html", "midi_8h" ]
];