var dir_6a6436ad46e42aad24bc1ce93af4f420 =
[
    [ "BLEMIDI", "dir_522ee7a08c8e28e6dc0c6f85802b0793.html", "dir_522ee7a08c8e28e6dc0c6f85802b0793" ],
    [ "USBMIDI", "dir_47a45441f873e4a267459ef119a0ab30.html", "dir_47a45441f873e4a267459ef119a0ab30" ],
    [ "BluetoothMIDI_Interface.hpp", "_bluetooth_m_i_d_i___interface_8hpp.html", "_bluetooth_m_i_d_i___interface_8hpp" ],
    [ "DebugMIDI_Interface.cpp", "_debug_m_i_d_i___interface_8cpp.html", null ],
    [ "DebugMIDI_Interface.hpp", "_debug_m_i_d_i___interface_8hpp.html", "_debug_m_i_d_i___interface_8hpp" ],
    [ "GenericBLEMIDI_Interface.hpp", "_generic_b_l_e_m_i_d_i___interface_8hpp.html", "_generic_b_l_e_m_i_d_i___interface_8hpp" ],
    [ "GenericBLEMIDI_Interface.ipp", "_generic_b_l_e_m_i_d_i___interface_8ipp.html", null ],
    [ "MIDI_Callbacks.hpp", "_m_i_d_i___callbacks_8hpp.html", "_m_i_d_i___callbacks_8hpp" ],
    [ "MIDI_Interface.cpp", "_m_i_d_i___interface_8cpp.html", "_m_i_d_i___interface_8cpp" ],
    [ "MIDI_Interface.hpp", "_m_i_d_i___interface_8hpp.html", "_m_i_d_i___interface_8hpp" ],
    [ "MIDI_Pipes.cpp", "_m_i_d_i___pipes_8cpp.html", null ],
    [ "MIDI_Pipes.hpp", "_m_i_d_i___pipes_8hpp.html", "_m_i_d_i___pipes_8hpp" ],
    [ "MIDI_Sender.hpp", "_m_i_d_i___sender_8hpp.html", "_m_i_d_i___sender_8hpp" ],
    [ "MIDI_Sender.ipp", "_m_i_d_i___sender_8ipp.html", null ],
    [ "MIDI_Staller.hpp", "_m_i_d_i___staller_8hpp.html", "_m_i_d_i___staller_8hpp" ],
    [ "PicoUSBInit.hpp", "_pico_u_s_b_init_8hpp.html", null ],
    [ "SerialMIDI_Interface.cpp", "_serial_m_i_d_i___interface_8cpp.html", null ],
    [ "SerialMIDI_Interface.hpp", "_serial_m_i_d_i___interface_8hpp.html", "_serial_m_i_d_i___interface_8hpp" ],
    [ "SoftwareSerialDebugMIDI_Interface.hpp", "_software_serial_debug_m_i_d_i___interface_8hpp.html", null ],
    [ "SoftwareSerialMIDI_Interface.hpp", "_software_serial_m_i_d_i___interface_8hpp.html", null ],
    [ "Teensy-USB-MIDI-name.c", "_teensy-_u_s_b-_m_i_d_i-name_8c.html", null ],
    [ "Teensy-USB-MIDI-name.py", "_teensy-_u_s_b-_m_i_d_i-name_8py.html", "_teensy-_u_s_b-_m_i_d_i-name_8py" ],
    [ "USBHostMIDI_Interface.hpp", "_u_s_b_host_m_i_d_i___interface_8hpp.html", "_u_s_b_host_m_i_d_i___interface_8hpp" ],
    [ "USBMIDI_Interface.hpp", "_u_s_b_m_i_d_i___interface_8hpp.html", "_u_s_b_m_i_d_i___interface_8hpp" ],
    [ "USBMIDI_Interface.ipp", "_u_s_b_m_i_d_i___interface_8ipp.html", null ],
    [ "USBMIDI_Sender.hpp", "_u_s_b_m_i_d_i___sender_8hpp.html", "_u_s_b_m_i_d_i___sender_8hpp" ]
];